spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: datastructuresece@gmail.com
    password: pmthdfhwmcaxslmw
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9002